### ISSUE TITLE
Paper titles

### ISSUE THREAD

**Issue by embaldridge** [weecology/sad-comparison#106]
Each chapter needs an actual title, and I am not very good with titles.

**Comment by embaldridge** [comment]
Potential titles for the whole thing:
A data driven approach to species abundance distributions.
A data driven approach to commonness and rarity
Original title for my original stuff (The commonness of rarity: A macroecological perspective)

**Comment by embaldridge** [comment]
Chapter 2: Clearly I am bad at this, as I call the dataset either Community Abundance Data or Miscellaneous Abundance Database.

**Comment by embaldridge** [comment]
Chapter 3:
Identifying non-neutrality with species abundance distributions.

**Comment by ethanwhite** [comment]
My initial suggestions:

* Diss: Data-intensive assessment of the species-abundance distribution
* Chapter 2: Community Abundance Data for Underrepresent Taxonomic Groups
* Chapter 3: Evaluating abundance distribution based signals of neutrality in the non-marine biosphere

**Comment by embaldridge** [comment]
I think I do actually have a couple of marine sites in chapter 3.

**Comment by ethanwhite** [comment]
* Chapter 3: Evaluating abundance distribution based signals of neutrality

**Comment by embaldridge** [comment]
Dissertation; A data-intensive assessment of the species abundance distribution. (I know I don't need the "A", but it makes me happier).
2: Community abundance data of underrepresented taxonomic groups.
3: Evaluating abundance distribution based signals of neutrality.

**Comment by ethanwhite** [comment]
Looks good to me!

**Comment by embaldridge** [comment]
Alrighty then, it's paperwork time!
