### ISSUE TITLE
More graphs

### ISSUE THREAD

**Issue by embaldridge** [weecology/sad-comparison#128]
Make graphs for chapter 3 with example abundance curves for Poisson lognormal and negative binomial.

Make map graph.

**Comment by embaldridge** [comment]
@ethanwhite , could you throw the lat long data for the other two datasets in the Dropbox?  I'm missing the Christmas birds and the butterflies.

**Comment by ethanwhite** [comment]
just dropped them in the chapter 3 folder.

**Comment by embaldridge** [comment]
I do not actually have a clue how to make the graphs for the example abundance curves.

**Comment by ethanwhite** [comment]
yeah, I have this at the top of the To Do list, just haven't had time with the SWC workshop and Dave in town. Hopefully this weekend.

**Comment by embaldridge** [comment]
I'm looking forward to see how it gets put together, so I will know how to do it the next time.
