### ISSUE TITLE
Duplicate values in some datasets

### ISSUE THREAD

**Issue by ethanwhite** [weecology/sad-comparison#165]
There are two kinds of duplicate values in some of the datasets:

1. Exact duplicates where the same combination of site, species and abundance. These are likely simply double entry of the same data points.
2. Duplicate site-species combinations but with different abundance values.

Actinopterygii, Arachnida, and Reptilia all have both of these issues. It is a small number of records in all cases, but should still be addressed.

**Comment by embaldridge** [comment]
Could you send me the results of your query so I can chase down the problems faster?

**Comment by embaldridge** [comment]
From a quick check, a few of these are fair, and are a morphospecies issue, most seem to be duplicates, a few are entry errors (challenging original source formatting, and a resulting mismatch between species and the correct abundance).  An initial attempt to fix things was heading down the road to introducing more errors so I reverted my edits, I'll probably end up solving these by re-entering the data from those sites, comparing the full records, then replacing the data for the problem sites en masse.  I'd also like to check my flags with your flags and make sure we are seeing the same ones.

**Comment by embaldridge** [comment]
Citation 12 is a mess, and has site numbers for half of the sites that belong to two other citations, which is messing up those citations, which are actually fine.  I need to chase down which sites are actually entered, then give the duplicate sites a new site code that leads to a correct site description and the appropriate citation.

**Comment by embaldridge** [comment]
Fixed.  All the things left should be things that look like errors, but are due to taxonomic resolution quirks in the source.  The database is updated on figshare, a pull request is in to the Retriever, and I'll start rerunning those groups as soon as I can get my database updated.

**Comment by ethanwhite** [comment]
Thanks!
