### ISSUE TITLE
One to one plot

### ISSUE THREAD

**Issue by embaldridge** [weecology/sad-comparison#167]
The one to one plot is broken.  SQL alchemy and pandas weren't playing, and pandas seems to have forgotten how to read_sql_table, so I simplified that so that it seems to import into a dataframe now.

I can't get the pivot table to work, I have no idea why it doesn't seem to understand index, but it gave me this:
TypeError: pivot_table() got an unexpected keyword argument 'index'

I suspect this graph won't look any different from the rest of the graphs, which don't look any different, but it still needs fixing.

@ethanwhite , thoughts?

**Comment by ethanwhite** [comment]
I suspect you have an older version of Pandas installed. Can you try
updating it and see if that fixes things.

**Comment by embaldridge** [comment]
I tried that first; it didn't help.

**Comment by embaldridge** [comment]
I tried sudo pip install pandas; I just tried sudo pip install pandas --upgrade.  Hopefully that will help once it finishes, my terminal window seems pretty excited about the whole thing.

**Comment by embaldridge** [comment]
Nope, still a problem.

**Comment by ethanwhite** [comment]
This runs fine for me on `master`. Can you do the following and see if the outputs match

```python
In [1]: import pandas

In [2]: pandas.__version__
Out[2]: '0.15.2'

In [3]: import sqlalchemy

In [4]: sqlalchemy.__version__
Out[4]: '0.9.8'
```

**Comment by ethanwhite** [comment]
Also, I don't think (but haven't checked) that the version in your PR will work because I think pandas needs an sqlalchemy engine, which is different from a connection via sqlite.

**Comment by embaldridge** [comment]
In [1]: import pandas

In [2]: pandas.__version__
Out[2]: '0.13.1'

In [3]: import sqlalchemy

In [4]: sqlalchemy.__version__
Out[4]: '1.0.0'

Thus, my attempting to upgrade to the latest version of pandas seems not to be working, or my environmental path is wrong, or something.  I'm trying to upgrade to the latest canopy distribution and see if that helps, but it's not done downloading yet.

I looked at the documentation before I started messing with things, and it said that read_sql_query can take either a SQLAlchemy engine or sqlite3, the same for read_sql.  read_sql_table has to have the SQLAlchemy engine.  I thought that since I am calling everything else with sqlite3, I might as well try to strip one extra dependency out.

**Comment by ethanwhite** [comment]
Ah, yeah, that's a pretty old version of pandas which should fix things. If read_sql_query doesn't care then I don't care :),

**Comment by embaldridge** [comment]
I sudo pip installed pandas --upgrade again, it told me it successfully installed pandas again, but this time it actually did successfully upgrade.  I have no idea why it didn't do it the first two times I tried, but who am I to argue with the capriciousness of computer gremlins.  The pull request version of the script works, and I added a close graphs statement just to keep things tidy.
