### ISSUE TITLE
Is relative_ll the same as AICc?

### ISSUE THREAD

**Issue by davharris** [weecology/sad-comparison#172]
From what I can tell, relative_ll is always the same as AICc.  For example, I see lines like this one:

`            relative_ll_logser_untruncated = AICc_logser_untruncated# Relative likelihood untruncated logseries
`

As far as I can tell, neither `AICc_logser_untruncated` nor `relative_ll_logser_untruncated` is ever modified again.

Could we just get rid of relative_ll?

**Comment by davharris** [comment]
Oh, I see. They're only equal sometimes.  Other times, one uses k1 and the other uses k2.

**Comment by ethanwhite** [comment]
Yeah, they are supposed to be based on this:
https://en.wikipedia.org/wiki/Likelihood_function#Relative_likelihood

I was envisioning them as a way to compare things in an AIC like way without the correction for the number of parameters.

**Comment by davharris** [comment]
Yeah, these could be interpreted as posterior weights if there were no prior favoring simpler models. I've re-computed them in a simpler way (e.g. not using the AIC function) and get the same answer.  Thanks for checking in.
