### ISSUE TITLE
cbc_spab.csv not found

### ISSUE THREAD

**Issue by davharris** [weecology/sad-comparison#174]
Looks like cbc_spab.csv is missing from the data folder.

**Comment by embaldridge** [comment]
It's in the chapter 1 subfolder.

**Comment by embaldridge** [comment]
Probably ought to mention that my abundance database datasets are in the
chapter 1 subfolder too.

**Comment by davharris** [comment]
I don't think that subfolder is in the repo?

**Comment by ethanwhite** [comment]
My recollection is that because we don't have permission to share some of the data, including CBC, that that data was being shared via a shared Dropbox folder that @davharris doesn't have access to.

**Comment by davharris** [comment]
Makes sense.  Probably the easiest thing would be for someone that already has access to the folder to run my test scripts, then.  I'll add the other data sets to the script so that this person can just run `python check.py` to see if everything is good.
