### ISSUE TITLE
Add discussion of Alroy 2015

### ISSUE THREAD

**Issue by ethanwhite** [weecology/sad-comparison#177]
Since we posted the preprint a new paper, Alroy 2015, came out. We can't fit his new distribution because it lacks a proper PMF, but we still need to discuss it.

**Comment by embaldridge** [comment]
#icanhazpdf?

**Comment by davharris** [comment]
Paper: http://advances.sciencemag.org/content/1/8/e1500082.full.pdf
Supplement: http://advances.sciencemag.org/highwire/filestream/186918/field_highwire_adjunct_files/0/1500082_SM.pdf

**Comment by embaldridge** [comment]
Thanks much!

**Comment by davharris** [comment]
Is this solved? We cite him twice now.

**Comment by ethanwhite** [comment]
Let's leave it open for the moment. Once I've read through if I think things match up with what I sent him via email I'll close it.
