### ISSUE TITLE
Final round of ms improvement

### ISSUE THREAD

**Issue by ethanwhite** [weecology/sad-comparison#179]
- [x] Dave
- [x] Xiao
- [x] Ethan
- [x] Elita

**Comment by davharris** [comment]
@ethanwhite @embaldridge If I want to make suggestions about manuscript texts, is the best approach to open a pull request with a modification chapter1.md?

**Comment by davharris** [comment]
I think this paragraph needs to be updated in a few ways:

>McGill et al. [-@mcgill2007] classified species abundance distribution models into five different families: purely statistical, branching process, population dynamics, niche partitioning, and spatial distribution of individuals. We evaluated models from each of the separate families, excluding the spatial distribution family, which requires spatially explicit data. Specifically, we evaluated the log-series, the Poisson log-normal, the negative binomial, the geometric distribution, and the Zipf distributions. All distributions were defined to be capable of having non-zero probability at values from 1 to infinity.

1) We're not using the geometric distribution anymore, right?
2) Does that mean we're no longer using all four of the non-spatial families?
3) Does the log-series distribution have nonzero mass for all finite abundance values?

**Comment by embaldridge** [comment]
I'm pro pull request.

**Comment by ethanwhite** [comment]
@davharris - if I understood things right the PR I merged this morning was just for the first half of the paper, is that right and are you still working on the second half?

@embaldridge - how do you want to run the additional work on editing? You recently made some changes so did you want to have @rueuntal or I work on it next and then do the final round of checks? Whatever route you want to go works fine for me.

**Comment by davharris** [comment]
Correct

Dave

**Comment by embaldridge** [comment]
@ethanwhite , your editing plan sounds good.

**Comment by ethanwhite** [comment]
OK, thanks @davharris. Let us know when you're done with your go through.

@rueuntal - do you want to take the next round or would you like me to do it?

**Comment by rueuntal** [comment]
I'd be happy to take the next round.

**Comment by ethanwhite** [comment]
Great. So @davharris will hand of to @rueuntal, who will hand off to me, and then @embaldridge will do a final round of cleanup. Getting close!

**Comment by davharris** [comment]
To clarify, should I finish before @rueuntal starts?

**Comment by rueuntal** [comment]
>To clarify, should I finish before @rueuntal starts?

That would probably be easier.

**Comment by ethanwhite** [comment]
> To clarify, should I finish before @rueuntal starts?

Yes, when you're done let @rueuntal know.

**Comment by davharris** [comment]
I'll basically be ready to sign off as soon as #199, #200, and #201 are addressed and the figures are all tidied up.

**Comment by ethanwhite** [comment]
Alright. Now that #213 is in we're down to @embaldridge for a final round of edits and #204!
