### ISSUE TITLE
Predicted RAD used in any analyses?

### ISSUE THREAD

**Issue by rueuntal** [weecology/sad-comparison#180]
I see that `sad-comparison.py` contains lines to generate obs-pred abundances based on logseries. Is this result used in any of the analyses? It doesn't seem to be the case, but just want to confirm before I remove the lines.

**Comment by ethanwhite** [comment]
I can't think of any reason why we'd have that now. @embaldridge?

**Comment by embaldridge** [comment]
I think it just followed the code from the METE paper that I used as a
starter and I forgot to remove it when I was cleaning up code last year.

Elita Baldridge, Ph.D.

GitHub: embaldridge
Twitter: @elitabaldridge
Website: http://elitabaldridge.org/

**Comment by rueuntal** [comment]
Thanks!
