### ISSUE TITLE
Figure 4

### ISSUE THREAD

**Issue by davharris** [weecology/sad-comparison#181]
I find Figure 4 difficult to read, mainly because the different histograms are so similar that everything becomes a purple blob.  I'm also not sure how useful the raw log-likelihoods are, since they probably depend primarily on N.

**Comment by ethanwhite** [comment]
I like the idea in #182 for presenting this data.

**Comment by davharris** [comment]
Here are the plots produced by `sad-postprocess.R` for the AICc and AICc weights:

![image](https://cloud.githubusercontent.com/assets/843017/15253434/4562f354-1900-11e6-9988-cd03ee8024dd.png)

![image](https://cloud.githubusercontent.com/assets/843017/15253443/4f11b228-1900-11e6-9154-e7bb3303ac9e.png)

Any improvements/suggestions/objections?

**Comment by embaldridge** [comment]
They look like lava lamps.

**Comment by davharris** [comment]
Just realized I included the wrong link for one of these.  It's fixed now.

**Comment by rueuntal** [comment]
Thanks, Dave! Maybe labeling the x-axis with the name of the distributions instead of AICc_? Everything else looks great (and they do look like lava lamps!).

**Comment by ethanwhite** [comment]
Looks great! Agree with @rueuntal on cleaning up the labels. Do you think we need both the deviation and the weight or that we should choose one of the two?

**Comment by davharris** [comment]
@ethanwhite I'd be fine with just using the weight, I think...

**Comment by davharris** [comment]
@embaldridge What do you think?

**Comment by embaldridge** [comment]
Works for me.
