### ISSUE TITLE
Figure 5

### ISSUE THREAD

**Issue by davharris** [weecology/sad-comparison#182]
As with Figure 4 (#181), I think that the raw likelihoods aren't tremendously useful. The tight correlations among the different log-likelihoods can probably be explained almost entirely by variation in N (and to a lesser extent, S), so I'm not sure we gain much by highlighting them.

My preference would probably be for the difference in log-likelihood scores (i.e. the height above or below the 1:1 line), which could be expressed as a bar graph.

**Comment by embaldridge** [comment]
I generally dislike bar graphs because the raw data is hidden in all the
summary.

Elita Baldridge, Ph.D.

GitHub: embaldridge
Twitter: @elitabaldridge
Website: http://elitabaldridge.org/

**Comment by davharris** [comment]
How about [violin plots](http://www.sthda.com/sthda/RDoc/figure/ggplot2/ggplot2-violin-plot-dot-plot-data-visualization-1.png <http://www.sthda.com/sthda/RDoc/figure/ggplot2/ggplot2-violin-plot-dot-plot-data-visualization-1.png>), then?

Dave

**Comment by embaldridge** [comment]
I like violin plots.

Elita Baldridge, Ph.D.

GitHub: embaldridge
Twitter: @elitabaldridge
Website: http://elitabaldridge.org/

**Comment by ethanwhite** [comment]
Yeah, we struggle with how to present these data. I'm fine with the difference in log-likelihood scores or the relative likelihoods presented as histogram/kernel density/violin.

**Comment by davharris** [comment]
Here are screenshots of the figures produced by `sad-postprocess.R` for the deviance and relative likelihood:

![image](https://cloud.githubusercontent.com/assets/843017/15253367/f1702168-18ff-11e6-885f-d90b80ef182f.png)

![image](https://cloud.githubusercontent.com/assets/843017/15253375/fb6f8a3c-18ff-11e6-9082-36926c4ef267.png)

Anything I should change/improve?

**Comment by ethanwhite** [comment]
I think cleaning up the distribution labels and and capitalizing `distribution` and we should be in good shape.
