### ISSUE TITLE
Dealing with input errors?

### ISSUE THREAD

**Issue by rueuntal** [weecology/sad-comparison#184]
I'm testing my code on Gentry but there are non-integer abundances in gentry_spab.csv. I'm assuming they are input errors in the original data? If being read in as integers, those number are converted in a strange way (e.g., 2.5 was converted into -1, which is how I detected it). Do we want to remove those entries, remove those sites, or round them up?

**Comment by ethanwhite** [comment]
Ugh. Gentry is such a mess. I think there was a site or two with mis-labeled column headers (in the raw data). I believe we've caught those since then in the retriever. Let me see if I can extract a new version and see if that fixes the problem (which is likely the result of the raw data mislabeling a size column as a count).

**Comment by rueuntal** [comment]
Thanks, Ethan. The site that I found with 2.5 is 102.

**Comment by embaldridge** [comment]
I think that the data in the subfolder for the project should have site 102
removed because of that problem.  I feel like there is a closed issue
floating about on that somewhere.

Elita Baldridge, Ph.D.

GitHub: embaldridge
Twitter: @elitabaldridge
Website: http://elitabaldridge.org/

**Comment by rueuntal** [comment]
Do we want to add the check in sad-comparisons.py, or is it already present
somewhere?

**Comment by ethanwhite** [comment]
Good memory @embaldridge. The close issues is #15.

**Comment by ethanwhite** [comment]
Looks like this is still an issue in Gentry, so let's go with the earlier decision to just drop 102.

**Comment by rueuntal** [comment]
Oh... The gentry_spab.csv file I used is probably not up to date then. :)
There's another site (179) that has the same problem. If no one objects,
I'll throw in a check for all abundances > 0 in `sad-comparisons.py` just
to be safe.

**Comment by ethanwhite** [comment]
Yeah, I'm looking at what is probably the same site right now and trying to line these up with existing issues in the queue for the retriever. So yes, sounds good.

**Comment by ethanwhite** [comment]
On the plus side, it looks like these are just straight up data entry errors by the original collectors with a missing column in a single row putting the wrong values in the wrong places... I guess that's a plus side :frowning:.

**Comment by rueuntal** [comment]
If it's not our fault then yes, definitely a plus side! Thanks folks, I'm
putting in the check and closing this.

**Comment by ethanwhite** [comment]
Two new issues in the Retriever opened thanks to finding this:
https://github.com/weecology/retriever/issues/415
https://github.com/weecology/retriever/issues/416

One of them we'll fix by changing that single line. The other I'm not even sure if we can understand enough to fix.

**Comment by ethanwhite** [comment]
Ah, now I understand what had happened with this on this project. The problem sites were removed from the data in our private data folder, but not from the ones in the public data folder. I'll go ahead and fix that so that testing should work as expected.
