### ISSUE TITLE
Likelihood versus deviance

### ISSUE THREAD

**Issue by davharris** [weecology/sad-comparison#192]
As I was working on the plotting code, I ran into a factor of -2 that tripped me up for a few minutes (AICc depends on -2*log-likelihood).  It occurred to me that this could trip up readers as well.

If we switched from graphing the log-likelihood to graphing the deviance (-2*log-likelihood), then the two measures would be easier for readers to compare.  The downside is that ecologists might be less familiar with the deviance, but we could include -2*log-likelihood in parentheses in the figure axes or caption to solve that.

What do you folks think?

**Comment by ethanwhite** [comment]
Good call. Going with deviance sounds good to me.

**Comment by rueuntal** [comment]
Sounds good to me too. I actually tripped over the -2 as well when going through @davharris 's code :)

**Comment by davharris** [comment]
Added to #191
