### ISSUE TITLE
lognormal vs. poisson-lognormal

### ISSUE THREAD

**Issue by davharris** [weecology/sad-comparison#200]
The paragraph about Ulrich keeps referring to the lognormal distribution.  Should that be Poisson-lognormal in all cases?

Here's the paragraph:

>A previous analysis of ~500 SADs comparing three models, concluded that the form of the distribution varied consistently between fully censused communities, best fit by the lognormal, and incompletely sampled communities, best fit by the Zipf and logseries [@ulrich2010]. The most completely sampled data in our analysis is arguably the forest inventories (Gentry, FIA), since these inventories count all trees above a certain stem diameter and detection of trees is straightforward so they are unlikely to be missed. The lognormal model is not the best fitting model in either of these datasets. The methods used by Ulrich et al. [@ulrich2010] involve the use of binning and fitting models to rank abundance plots, which deviates from the best practices [@matthews2014] used in this paper. A comparison of these two studies with equivalent methods will be necessary to resolve the discrepancies with respect to the influence of sampling on the observed form of the SAD.

**Comment by ethanwhite** [comment]
I don't remember which one they use. It's not uncommon for folks to use the continuous log-normal so we'd need to check.

**Comment by davharris** [comment]
[Looks like he used the plain-old lognormal](http://www.keib.umk.pl/wp-content/uploads/2013/02/Oikos2010.pdf). Now we have to reconcile them. Ugh.

**Comment by davharris** [comment]
fixed in #213
