### ISSUE TITLE
feasible sets

### ISSUE THREAD

**Issue by davharris** [weecology/sad-comparison#201]
I'm having some trouble wrapping my head around what's going on in the final paragraph.  My understanding is that the feasible set approach is all about rank abundance curves, and doesn't really have much to say directly about SADs.

As far as I can tell, there's no upper bound on how badly a SAD can fit and no reason to expect that most distributions would do well at all.  A Poisson distribution without any overdispersion would probably fit terribly, for instance.

Am I missing something?

**Comment by ethanwhite** [comment]
We look directly at the SAD as well, see Figure 1. If you look at all of the possible ways you can place N individuals into S species most of the empirical distributions will have the same general shape. Your definitely right that it's easy to pick models that don't follow that shape and some of the most natural initial choices (like the Poisson) would yield really poor fits. I'm happy to drop the last paragraph and/or replace it with something else.

**Comment by davharris** [comment]
Okay, I tried reorganizing things in #199. I still reference Frank and Locey&White, but don't focus explicitly on feasible sets.

**Comment by davharris** [comment]
Closing, since this was resolved/merged in #199.
