### ISSUE TITLE
Add discussion of failure of Zipf compared to earlier work

### ISSUE THREAD

**Issue by ethanwhite** [weecology/sad-comparison#203]

**Comment by davharris** [comment]
Does "previous work" just mean Ulrich et al., or is it much broader?

**Comment by ethanwhite** [comment]
I was just thinking of Ulrich when I read this.

**Comment by davharris** [comment]
Do we need to say anything more than "their methods are less reliable"?

**Comment by ethanwhite** [comment]
Nope. This was just a reminder to myself to make sure I added it when I got
to that point.

**Comment by ethanwhite** [comment]
This is actually already well handled in the Discussion (which I hadn't gotten to yet in this read through). Closing in favor of #206 which will broaden the existing paragraph.
