### ISSUE TITLE
Provide detailed legends for violin plots

### ISSUE THREAD

**Issue by ethanwhite** [weecology/sad-comparison#207]

**Comment by davharris** [comment]
@ethanwhite What do you have in mind? Currently, I think the manuscript only refers to the AICc weights plot (as figure 3) and not the other plots.  If we only end up using that one, do we still want a legend?

**Comment by ethanwhite** [comment]
Given the writing you've done in the first paragraph (which I like) I think we probably need to include figures for this. The olds figures are currently included in the ms at the end of the results:

```
![Log-likelihoods by model for all datasets combined.](./sad-data/chapter1/likelihoods.png)

![Log-likelihoods by model for all datasets combined.](./sad-data/chapter1/likelihoods_one_to_one.png)
```

**Comment by ethanwhite** [comment]
The easiest thing to do might be to add some language here and I'll add it to avoid us stepping on each others toes with commits.

**Comment by ethanwhite** [comment]
I'm taking care of this.
