### ISSUE TITLE
Cleanup figures

### ISSUE THREAD

**Issue by ethanwhite** [weecology/sad-comparison#217]
Look over figures and do any needed cleanup to make publication quality. In particular one reviewer noted some issues with axis label size.

> 1) Please use numbers to name your files, example: Fig1.eps, Fig2.png.

> 2) Please combine any figures with multiple parts into single, labeled, figure files. Ex: Figs 1A and 1B should be one figure grouping the parts either next to each other or one on top of the other and only labeled “A” and “B” on the respective figure parts. Each figure with multiple parts should label each part alphabetically (e.g. A, B, C) and all parts should be submitted together in one file.

> 3) In addition to providing low res files embedded in the manuscript, please upload your high res figures in either EPS, PNG, JPG (photographs only) or PDF (vector PDF's only) as primary files here <https://peerj.com/manuscripts/12365/files> as these will be needed at production. Note: You have chosen to submit the reviewing manuscript as a 'single PDF' and so these higher resolution figures won't be merged with that document, just used at production.

> 4) Figures should be at least 900 by 900 pixels (without unnecessary white space around them).

- [x] general figure cleanup
- [x] include png/pdf image files
- [x] label subplots if necessary

**Comment by davharris** [comment]
I think Figure 4 has too many panels for everything to fit as a bar graph. Exploring other options...

**Comment by ethanwhite** [comment]
I think this is the last thing that needs to be done before we're ready to go. @davharris - let me know if there's anything I can do to help.

**Comment by davharris** [comment]
How's this look?

![wins-by-dataset](https://cloud.githubusercontent.com/assets/843017/20183857/ca4f76ce-a734-11e6-89df-6c50bb6f455c.png)

**Comment by ethanwhite** [comment]
I like it. Two thoughts:

1. Is that a color blind approved palette?
2. Given how PeerJ is laid out I think 4x3 might be better than 3x4.

**Comment by ethanwhite** [comment]
> Given how PeerJ is laid out I think 4x3 might be better than 3x4.

Actually, never mind, I forgot that they will do figures full width unlike the text. I think this is fine.

**Comment by davharris** [comment]
I thought it was safe, but it turns out the palette is only good for dichromats up to 3 colors. How's this?

![wins-by-dataset](https://cloud.githubusercontent.com/assets/843017/20187528/a676daae-a742-11e6-8f91-5a2f6d2f8d8c.png)

**Comment by davharris** [comment]
I think I might like 3x4 better, but I don't feel strongly.  Unfortunately, I can't make it much narrower without shrinking the font or hyphenating "negative", "binomial", "poisson", and "lognormal."

**Comment by davharris** [comment]
note to self: Add consistent color scheme across figures

**Comment by davharris** [comment]
Can someone change the example-plot.py code so that it uses these colors and matches the ones we're using elsewhere? Thanks!

"#990F0F" "#99700F" "#1F990F" "#710F99"

**Comment by davharris** [comment]
I'm ready to sign off on this as soon as the colors in `example-plot.py` are updated. For whatever reason (Python 2 vs 3?) I can't get macroecotools to run on my machine anymore.

**Comment by ethanwhite** [comment]
Looks like this is all finished as of #226.
