### ISSUE TITLE
Sign offs

### ISSUE THREAD

**Issue by ethanwhite** [weecology/sad-comparison#223]
Check the box next to your name once you think the revised ms is ready to go:

- [x] @embaldridge 
- [x] @davharris 
- [x] @rueuntal 
- [x] @ethanwhite

**Comment by rueuntal** [comment]
Sorry to have been lagging behind! All changes look great. Before signing off, are there any remaining pieces that I can contribute to?

**Comment by ethanwhite** [comment]
@rueuntal no problem at all. If you have a few minutes and want to review and (if they're ready) merge my three minor PRs that would be great.

**Comment by davharris** [comment]
I've signed off now as well.

**Comment by ethanwhite** [comment]
@embaldridge just signed off on this over email.
