### ISSUE TITLE
Consider a new macroecotools release

### ISSUE THREAD

**Issue by ethanwhite** [weecology/sad-comparison#227]
For some reason we have a version mismatch between GitHub/Zenodo and Pypi. Pypi things 0.3 is from two years ago, so if someone were to try to reproduce using a standard `pip install macroecotools` they would end up failing.

**Comment by rueuntal** [comment]
Hmmm it seemed to have worked on my computer.

**Comment by ethanwhite** [comment]
Done:

https://pypi.python.org/pypi/macroecotools
https://zenodo.org/record/166721
