### ISSUE TITLE
Compare negative binomial fitting to another implementation

### ISSUE THREAD

**Issue by ethanwhite** [weecology/sad-comparison#93]
Fitting the negative binomial is known to be a little tricky, so we should compare the fits we're getting to another implementation.

**Comment by rueuntal** [comment]
I'll look into this when I've got the time, hopefully next week.

**Comment by rueuntal** [comment]
The R code to obtain the ML parameters for negative binomial is:
```
library(MASS)
get_n_p_negbin = function(num_list){
  pars = fitdistr(num_list, 'negative binomial')
  n = as.numeric(pars$est[1])
  mu = as.numeric(pars$est[2])
  p = n / (n + mu)
  return(c(n, p))
}
```
The two numbers returned by this function, n and p, are directly comparable to the output of ```md.negbin_solver()```.

**Comment by ethanwhite** [comment]
Thanks @rueuntal. Some quick checks suggest that the parameters are matching pretty well. Can you give me an equivalent code snipped for getting the log-likelihood in R? Thanks.

**Comment by rueuntal** [comment]
You mean the log-likelihood of the negative binomial?

**Comment by ethanwhite** [comment]
yes.

**Comment by rueuntal** [comment]
Sorry, I just realized something - the negative binomial we are using in Python is lower-truncated at 1, while the default in R starts from zero, so the solvers probably cannot be directly matched to each other. I'll see if there's anything equivalent in R where the zeros are excluded.

**Comment by rueuntal** [comment]
These two functions should do, let me know if anything doesn't look right: 
```
library(VGAM)

get_n_p_negbin = function(num_list){
  pars = Coef(vglm(num_list ~ 1, posnegbinomial))
  mu = as.numeric(pars)[1]
  n = as.numeric(pars)[2]
  p = n / (n + mu)
  return(c(n, p))
}

get_negbin_ml = function(num_list, n, p){
  ml = sum(dnbinom(num_list, n, p, log = T)) - length(num_list) * log(1 - dnbinom(0, n, p))
  return(ml)
}
```

**Comment by ethanwhite** [comment]
Thanks @rueuntal. When running this I'm currently getting the following error:

```R
> get_n_p_negbin(c(1,1,1,2,5,10,50))
Error in Coef(vglm(num_list ~ 1, posnegbinomial)) : 
  error in evaluating the argument 'object' in selecting a method for function 'Coef': Error in if (take.half.step) { : missing value where TRUE/FALSE needed
```

**Comment by ethanwhite** [comment]
Looks like the problem is with the `vglm` call:

```R
> vglm(c(1,1,1,2,5,10,50) ~ 1, posnegbinomial)
Error in if ((temp <- sum(wz[, 1:M, drop = FALSE] < wzepsilon))) warning(paste(temp,  : 
  argument is not interpretable as logical
```

**Comment by rueuntal** [comment]
I'm guessing that the internal algorithm fails for some of the lists, but vglm is too complicated for me to trouble shoot. This is the only built-in function that I found in R which estimates parameters for the zero-truncated negative binomial though. We can absolutely write our own but I'm not sure how different that would be from the Python implementation, besides the optimization algorithm. What do you think?

**Comment by ethanwhite** [comment]
I'd just gotten there myself. It was an issue with the toy dataset I threw at it. I'll try it on some real data and go from there. Sorry for the red herring.

**Comment by ethanwhite** [comment]
https://en.wikipedia.org/wiki/Red_herring just in case you hadn't picked up that idiom yet :)

**Comment by rueuntal** [comment]
Thanks for the reference :) I'd guess that the error would probably show up for some empirical SADs too, which if I remember correctly are as outrageous as any artificial ones. But as a rudimentary test it's probably OK.

**Comment by ethanwhite** [comment]
A few quick comparisons using the Actinopterygii data suggest that when R converges (which is substantially more rarely than Python) they give very similar results for both MLEs and log-likehoods. In general it looks like things are working well. Thanks again for the help @rueuntal!

**Comment by rueuntal** [comment]
My pleasure! Glad to hear Python handles negative binomial well.

**Comment by davharris** [comment]
For what it's worth, I re-implemented this in R (`check-outputs.R`) and get very similar results as well. Now that I look at macroecotools, I think my code is identical to @rueuntal's except for some minor order of operations stuff.

BTW, Is there a higher-precision way to calculate `log(1 - p)` for small `p`? I thought that there was one, but I can only find high-precision methods for `log(1 + p)`.

**Comment by davharris** [comment]
It just occurred to me that we could skip the `log(1-p)` calculation entirely by using tail probabilities instead of probability mass functions.  In R, this would mean switching from 

`log(1 - dnbinom(0, size = 3, mu = 3))`

to

`pnbinom(0, size = 3, mu = 3, lower.tail = FALSE, log.p = TRUE)`

I'm not sure what the equivalent `stats.nbinom` call would be, but it could make a difference in cases where most of the probability mass is at zero.

**Comment by davharris** [comment]
Looks like the equivalent Python code would use `logsf`

**Comment by ethanwhite** [comment]
Negative binomial is now being fit in R as that appears to be the most robust approach.
