### ISSUE TITLE
Add discussion of Connolly 2014

### ISSUE THREAD

**Issue by ethanwhite** [weecology/sad-comparison#97]
Very important paper for us to discuss:
http://www.pnas.org/content/111/23/8524.full.pdf+html

**Comment by embaldridge** [comment]
On fish: Of 48 citations, 30 were freshwater, mostly rivers, but some reservoirs and lakes, 5 were estuaries, and 13 were marine, mostly intertidal/near shore, mangrove areas.  Nothing deep water.
