### ISSUE TITLE
Add head to head comparison of lognormal and negative-binomial

### ISSUE THREAD

**Issue by ethanwhite** [weecology/sad-comparison#98]
Then central results of [Connolly et al. 2014](http://www.pnas.org/content/111/23/8524.full.pdf+html) is that the lognormal fits data better than the negative-binomial (Poisson-gamma in their language), which allows them to reject the neutral model. It would be interesting to redo this comparison since they seem very similar in our analysis.

Part of this would need to include their analysis of how the difference changes as a function of "the number of distinct abundance values" (or perhaps better, the number of species). This would be interesting to add anyway.

**Comment by rueuntal** [comment]
Do we want a function to reproduce something like Fig. 2B in Connolly et al., i.e., median number of distinct abundance values versus mean relative likelihood between the two?

**Comment by ethanwhite** [comment]
Yes, assuming that mean relative likelihood and mean AICc weight are identical (which I suspect they are).

**Comment by davharris** [comment]
@ethanwhite I agree they should be the same, since poisson-lognormal and poisson-gamma have the same number of free parameters.

**Comment by ethanwhite** [comment]
This has now been moved off into a separate collaboration with Connolly (as of sometime in Spring of 2015).
